[workspace]
resolver = "2"

members = ["day-*"]
exclude = ["day-5"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
nom = {  version = "7.1.3" }
thiserror = "1.0.50"
